// Comprehensive Course Database for all specified universities (UG and PG courses)
export const courses = [
    // --- ADTU (Online) ---
    {
        id: "adtu-bca",
        title: "Online Bachelor of Computer Applications (BCA)",
        university: "ADTU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 120000,
        rating: 4.4,
        reviewsCount: 180,
        type: "Recorded Lectures + Live Q&A",
        eligibility: "10+2 or equivalent from recognized board",
        careerSupport: true,
        syllabus: ["Programming in C", "Data Structures", "Database Management", "Software Engineering"],
        imageColor: "linear-gradient(135deg, #1b3a4b, #212529)"
    },
    {
        id: "adtu-mba",
        title: "Online MBA in Human Resource Management",
        university: "ADTU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 180000,
        rating: 4.5,
        reviewsCount: 220,
        type: "100% Online with LMS",
        eligibility: "Bachelor's degree with 50% marks",
        careerSupport: true,
        syllabus: ["Organizational Behavior", "Talent Acquisition", "Labour Laws", "Performance Management"],
        imageColor: "linear-gradient(135deg, #1b3a4b, #3d5a80)"
    },

    // --- Alliance (Online) ---
    {
        id: "alliance-bba",
        title: "Online Bachelor of Business Administration (BBA)",
        university: "Alliance (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 195000,
        rating: 4.6,
        reviewsCount: 310,
        type: "Live Cohort Classes",
        eligibility: "10+2 from a recognized board",
        careerSupport: true,
        syllabus: ["Marketing Principles", "Microeconomics", "Business Math", "Consumer Behaviour"],
        imageColor: "linear-gradient(135deg, #1d3557, #457b9d)"
    },
    {
        id: "alliance-mba",
        title: "Online MBA (General Management)",
        university: "Alliance (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 280000,
        rating: 4.7,
        reviewsCount: 450,
        type: "Blended Live Sessions",
        eligibility: "Graduate degree with 50% aggregate",
        careerSupport: true,
        syllabus: ["Corporate Strategy", "Managerial Economics", "Financial Management", "International Business"],
        imageColor: "linear-gradient(135deg, #1d3557, #e63946)"
    },

    // --- Amrita (Online) ---
    {
        id: "amrita-bca",
        title: "Online BCA in Data Science",
        university: "Amrita (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 165000,
        rating: 4.7,
        reviewsCount: 650,
        type: "Online Live & Interactive",
        eligibility: "12th standard with Math/CS background",
        careerSupport: true,
        syllabus: ["Python for Data Science", "Data Visualization", "SQL Database Fundamentals", "Intro to AI"],
        imageColor: "linear-gradient(135deg, #4a148c, #7b1fa2)"
    },
    {
        id: "amrita-mba",
        title: "Online MBA (Core Specializations)",
        university: "Amrita (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 220000,
        rating: 4.8,
        reviewsCount: 1210,
        type: "Dual Specialization / Live Interaction",
        eligibility: "UG degree with min 50% marks",
        careerSupport: true,
        syllabus: ["Financial Analytics", "Supply Chain", "HR Strategy", "Marketing Analytics"],
        imageColor: "linear-gradient(135deg, #4a148c, #ab47bc)"
    },

    // --- Andhra (Online) ---
    {
        id: "andhra-ba",
        title: "Online Bachelor of Arts (BA - Economics & History)",
        university: "Andhra (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Arts / Humanities",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 75000,
        rating: 4.3,
        reviewsCount: 420,
        type: "Recorded & Semester Exams",
        eligibility: "12th Standard or equivalent",
        careerSupport: false,
        syllabus: ["Indian History", "Microeconomics", "Macroeconomics", "Sociology Fundamentals"],
        imageColor: "linear-gradient(135deg, #0d1b2a, #1b263b)"
    },
    {
        id: "andhra-mba",
        title: "Online MBA (Finance / Marketing)",
        university: "Andhra (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 150000,
        rating: 4.5,
        reviewsCount: 880,
        type: "Regular online assessment & webinars",
        eligibility: "Graduate degree",
        careerSupport: true,
        syllabus: ["Financial Management", "Consumer Behavior", "Taxation Laws", "Sales & Distribution"],
        imageColor: "linear-gradient(135deg, #0d1b2a, #415a77)"
    },

    // --- AU (Online) ---
    {
        id: "au-bba",
        title: "Online BBA in Digital Marketing",
        university: "AU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 140000,
        rating: 4.4,
        reviewsCount: 290,
        type: "LMS Enabled Study + Self Paced",
        eligibility: "10+2 pass (any stream)",
        careerSupport: true,
        syllabus: ["Search Engine Optimization", "Social Media Marketing", "Content Strategy", "Digital Analytics"],
        imageColor: "linear-gradient(135deg, #2b2d42, #8d99ae)"
    },
    {
        id: "au-mba",
        title: "Online MBA (Business Analytics)",
        university: "AU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 210000,
        rating: 4.6,
        reviewsCount: 410,
        type: "Weekly webinars + Assessments",
        eligibility: "Graduation with Math/Commerce background preferred",
        careerSupport: true,
        syllabus: ["Predictive Modelling", "R & Python for Managers", "Data warehousing", "Strategic Decisions"],
        imageColor: "linear-gradient(135deg, #2b2d42, #ef233c)"
    },

    // --- Bennett (Online) ---
    {
        id: "bennett-bca",
        title: "Online BCA (Cloud & Cybersecurity)",
        university: "Bennett (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 180000,
        rating: 4.6,
        reviewsCount: 390,
        type: "LMS + Practical Labs",
        eligibility: "10+2 with minimum 50% marks",
        careerSupport: true,
        syllabus: ["Cloud Virtualization", "Ethical Hacking", "Operating Systems", "Computer Networks"],
        imageColor: "linear-gradient(135deg, #0f2027, #203a43)"
    },
    {
        id: "bennett-mba",
        title: "Online MBA in Digital Business",
        university: "Bennett (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 260000,
        rating: 4.7,
        reviewsCount: 520,
        type: "Interactive Live Cohorts",
        eligibility: "Bachelor's degree with 50% aggregate",
        careerSupport: true,
        syllabus: ["E-Commerce Strategy", "Digital Product Management", "Data Analytics", "Growth Hacking"],
        imageColor: "linear-gradient(135deg, #0f2027, #2c5364)"
    },

    // --- Christ (Online) ---
    {
        id: "christ-bba",
        title: "Online BBA in Finance & Accounting",
        university: "Christ (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 250000,
        rating: 4.8,
        reviewsCount: 840,
        type: "Blended Hybrid Learning",
        eligibility: "Class 12th passed with min 60%",
        careerSupport: true,
        syllabus: ["Corporate Accounting", "Cost Management", "Tax planning", "Financial Institutions"],
        imageColor: "linear-gradient(135deg, #0a1128, #001f54)"
    },
    {
        id: "christ-mba",
        title: "Online MBA in Executive Leadership",
        university: "Christ (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 320000,
        rating: 4.9,
        reviewsCount: 960,
        type: "Live classes + Case study models",
        eligibility: "Graduation with 55% marks + Interview",
        careerSupport: true,
        syllabus: ["Leadership styles", "Strategic Alliances", "Conflict Resolution", "Global Markets"],
        imageColor: "linear-gradient(135deg, #0a1128, #1282a2)"
    },

    // --- CUOL (Online) ---
    {
        id: "cuol-bca",
        title: "Online BCA (General Computer Applications)",
        university: "CUOL (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 110000,
        rating: 4.5,
        reviewsCount: 1450,
        type: "100% Online Self-Paced",
        eligibility: "12th Standard Passed",
        careerSupport: true,
        syllabus: ["C++ Programming", "Web Design", "Computer Architecture", "Database Systems"],
        imageColor: "linear-gradient(135deg, #ff7b00, #ffb703)"
    },
    {
        id: "cuol-mca",
        title: "Online MCA in AI & Machine Learning",
        university: "CUOL (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 150000,
        rating: 4.6,
        reviewsCount: 1890,
        type: "Self-Paced with Faculty Mentors",
        eligibility: "Graduation with BCA/B.Sc. CS or Math",
        careerSupport: true,
        syllabus: ["Supervised ML", "Deep Learning Tools", "Python Coding", "Statistical Inference"],
        imageColor: "linear-gradient(135deg, #ff7b00, #fb8500)"
    },

    // --- DPU Mumbai (Online) ---
    {
        id: "dpumumbai-bba",
        title: "Online Bachelor of Business Administration",
        university: "DPU Mumbai (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 135000,
        rating: 4.4,
        reviewsCount: 390,
        type: "Recorded Lectures & PDF Notes",
        eligibility: "12th Standard in any stream",
        careerSupport: true,
        syllabus: ["Managerial Accounting", "Organizational Theory", "Retail Management", "B2B Marketing"],
        imageColor: "linear-gradient(135deg, #2b0f54, #ab47bc)"
    },
    {
        id: "dpumumbai-mba",
        title: "Online MBA in Retail & Finance",
        university: "DPU Mumbai (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 175000,
        rating: 4.5,
        reviewsCount: 520,
        type: "Online Assessment portal",
        eligibility: "Graduation from recognized board",
        careerSupport: true,
        syllabus: ["Supply Chain in Retail", "Security Analysis", "Merchandising Strategy", "Portfolio Management"],
        imageColor: "linear-gradient(135deg, #2b0f54, #ea80fc)"
    },

    // --- DPU Pune (Online) ---
    {
        id: "dpupune-bba",
        title: "Online BBA (IT & Systems Management)",
        university: "DPU Pune (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 140000,
        rating: 4.5,
        reviewsCount: 680,
        type: "Webinar sessions & Online Exams",
        eligibility: "12th Standard Pass",
        careerSupport: true,
        syllabus: ["Management Info Systems", "Software Project Basics", "Database for Managers", "Business Analytics"],
        imageColor: "linear-gradient(135deg, #420626, #b0003a)"
    },
    {
        id: "dpupune-mba",
        title: "Online MBA (Core Management Options)",
        university: "DPU Pune (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 160000,
        rating: 4.6,
        reviewsCount: 980,
        type: "LMS Assessment Modules",
        eligibility: "Bachelor's degree with 50% aggregate",
        careerSupport: true,
        syllabus: ["Marketing Management", "Strategic Policy", "Corporate Governance", "International Trade"],
        imageColor: "linear-gradient(135deg, #420626, #d81b60)"
    },

    // --- Galgotias (Online) ---
    {
        id: "galgotias-bca",
        title: "Online BCA (Mobile App Development)",
        university: "Galgotias (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 110000,
        rating: 4.4,
        reviewsCount: 820,
        type: "Online lectures + LMS",
        eligibility: "12th Standard from any stream",
        careerSupport: true,
        syllabus: ["Android Programming", "iOS Fundamentals", "UX/UI Design", "Backend APIs"],
        imageColor: "linear-gradient(135deg, #03001e, #7303c0)"
    },
    {
        id: "galgotias-mca",
        title: "Online MCA (Cloud Infrastructure)",
        university: "Galgotias (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 145000,
        rating: 4.5,
        reviewsCount: 710,
        type: "Recorded & Virtual Labs",
        eligibility: "BCA / Bachelor's in CS / IT",
        careerSupport: true,
        syllabus: ["Cloud Storage", "Virtualization Systems", "Datacenter Operations", "Linux Scripting"],
        imageColor: "linear-gradient(135deg, #03001e, #ec38bc)"
    },

    // --- GLA (Online) ---
    {
        id: "gla-bca",
        title: "Online BCA (Web Development)",
        university: "GLA (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 105000,
        rating: 4.3,
        reviewsCount: 390,
        type: "Semester Based LMS learning",
        eligibility: "12th Standard Passed",
        careerSupport: true,
        syllabus: ["HTML/CSS/JS", "Node.js & Databases", "PHP Development", "Web Application Architecture"],
        imageColor: "linear-gradient(135deg, #000428, #004e92)"
    },
    {
        id: "gla-mca",
        title: "Online MCA in Software Development",
        university: "GLA (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 135000,
        rating: 4.5,
        reviewsCount: 460,
        type: "Live Weekend Lectures",
        eligibility: "BCA/B.Sc. in CS or Mathematics in 12th",
        careerSupport: true,
        syllabus: ["Advanced Software Engineering", "Object-oriented Frameworks", "Design Patterns", "Agile Methodologies"],
        imageColor: "linear-gradient(135deg, #000428, #0083b0)"
    },

    // --- JU (Online) ---
    {
        id: "ju-bba",
        title: "Online BBA (Core Business Administration)",
        university: "JU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 130000,
        rating: 4.5,
        reviewsCount: 980,
        type: "Self-Paced with Mentor support",
        eligibility: "12th Pass (any stream)",
        careerSupport: true,
        syllabus: ["Principles of Management", "Marketing Strategy", "Business Law", "HR Management"],
        imageColor: "linear-gradient(135deg, #114b5f, #028090)"
    },
    {
        id: "ju-mca",
        title: "Online MCA in Full Stack Development",
        university: "JU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 180000,
        rating: 4.6,
        reviewsCount: 1100,
        type: "Interactive Cohorts & Projects",
        eligibility: "BCA / Graduate with Math background",
        careerSupport: true,
        syllabus: ["Frontend frameworks (React/Vue)", "Backend with Node & Express", "Deployment & CI/CD", "DBMS"],
        imageColor: "linear-gradient(135deg, #114b5f, #f45b69)"
    },

    // --- KUK (Online) ---
    {
        id: "kuk-ba",
        title: "Online Bachelor of Arts (BA General)",
        university: "KUK (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Arts / Humanities",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 55000,
        rating: 4.1,
        reviewsCount: 310,
        type: "Material Dispatch + Online Submissions",
        eligibility: "10+2 or equivalent",
        careerSupport: false,
        syllabus: ["English Literature", "Political Science", "Sanskrit studies", "History of India"],
        imageColor: "linear-gradient(135deg, #37000c, #73001c)"
    },
    {
        id: "kuk-mba",
        title: "Online MBA (Core Management)",
        university: "KUK (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 120000,
        rating: 4.3,
        reviewsCount: 480,
        type: "Online LMS + Mid-term Assignments",
        eligibility: "Bachelor's degree from recognized university",
        careerSupport: false,
        syllabus: ["Managerial Finance", "Organization Behavior", "Business Communication", "Market Research"],
        imageColor: "linear-gradient(135deg, #37000c, #c3073f)"
    },

    // --- LPU (Online) ---
    {
        id: "lpu-bca",
        title: "Online Bachelor of Computer Applications (BCA)",
        university: "LPU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 87000,
        rating: 4.4,
        reviewsCount: 3200,
        type: "LPU e-Connect LMS Portal",
        eligibility: "12th Standard Passed",
        careerSupport: true,
        syllabus: ["Programming Concepts", "Database Management", "HTML and CSS", "Network Security Basics"],
        imageColor: "linear-gradient(135deg, #d35400, #e67e22)"
    },
    {
        id: "lpu-mba",
        title: "Online MBA (Dual Specializations)",
        university: "LPU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 130000,
        rating: 4.6,
        reviewsCount: 4600,
        type: "LMS + Academic Counseling",
        eligibility: "Bachelor's degree with 50% marks",
        careerSupport: true,
        syllabus: ["International Marketing", "Derivatives and Risk Management", "Product Strategy", "Consumer Analytics"],
        imageColor: "linear-gradient(135deg, #d35400, #f39c12)"
    },

    // --- MAHE (Online) ---
    {
        id: "mahe-mba",
        title: "Online Master of Business Administration",
        university: "MAHE (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 300000,
        rating: 4.8,
        reviewsCount: 2200,
        type: "Live Interactive Lectures & Projects",
        eligibility: "Graduation with 50% aggregate marks",
        careerSupport: true,
        syllabus: ["Marketing Analytics", "Advanced Corporate Finance", "Operations Strategy", "Digital Leadership"],
        imageColor: "linear-gradient(135deg, #2b1055, #7597de)"
    },
    {
        id: "mahe-mca",
        title: "Online MCA in Systems Design",
        university: "MAHE (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 260000,
        rating: 4.7,
        reviewsCount: 1890,
        type: "Webinar based live training + labs",
        eligibility: "BCA/B.Sc. in CS or Mathematics in 12th",
        careerSupport: true,
        syllabus: ["Software Architectures", "Modern DBMS", "Cryptography", "Enterprise Networking"],
        imageColor: "linear-gradient(135deg, #2b1055, #7b1fa2)"
    },

    // --- MUJ (Online) ---
    {
        id: "muj-bca",
        title: "Online BCA (General Track)",
        university: "MUJ (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 135000,
        rating: 4.5,
        reviewsCount: 1650,
        type: "Mobile app enabled self-paced courses",
        eligibility: "12th Standard Passed",
        careerSupport: true,
        syllabus: ["C Programming", "Discrete Mathematics", "Data Communication", "Java Basics"],
        imageColor: "linear-gradient(135deg, #0f4c81, #1f77b4)"
    },
    {
        id: "muj-mca",
        title: "Online MCA (Advanced Application Dev)",
        university: "MUJ (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 180000,
        rating: 4.7,
        reviewsCount: 2200,
        type: "Live classes + Industry expert talks",
        eligibility: "BCA / Bachelor's in CS / IT",
        careerSupport: true,
        syllabus: ["Mobile App Development", "Advanced Web Programming", "Cloud Systems", "Deep Learning Basics"],
        imageColor: "linear-gradient(135deg, #0f4c81, #5c6bc0)"
    },

    // --- NMIMS (Online) ---
    {
        id: "nmims-bba",
        title: "Online BBA in Brand Management",
        university: "NMIMS (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 240000,
        rating: 4.7,
        reviewsCount: 2900,
        type: "LMS webinars + Self Study",
        eligibility: "12th pass with minimum 50% marks",
        careerSupport: true,
        syllabus: ["Brand Strategy", "Consumer Insights", "Retail Operations", "Advertising Principles"],
        imageColor: "linear-gradient(135deg, #780016, #b71c1c)"
    },
    {
        id: "nmims-mba",
        title: "Online MBA (Core Management Strategy)",
        university: "NMIMS (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 350000,
        rating: 4.8,
        reviewsCount: 5200,
        type: "Live Classes + Extensive Industry Placement Support",
        eligibility: "UG graduation with 50% aggregate + Work experience preferred",
        careerSupport: true,
        syllabus: ["Corporate Finance", "Operations Analytics", "Strategic Design", "Talent Management"],
        imageColor: "linear-gradient(135deg, #780016, #d32f2f)"
    },

    // --- PU (Online) ---
    {
        id: "pu-bba",
        title: "Online BBA (General Business)",
        university: "PU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 95000,
        rating: 4.2,
        reviewsCount: 240,
        type: "Self-study + Periodic webinars",
        eligibility: "12th Standard Passed",
        careerSupport: false,
        syllabus: ["Introduction to Commerce", "Marketing Baselines", "Communication Skills", "Office Management"],
        imageColor: "linear-gradient(135deg, #0e1e38, #1d3557)"
    },
    {
        id: "pu-mba",
        title: "Online MBA (Marketing Management)",
        university: "PU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 140000,
        rating: 4.4,
        reviewsCount: 390,
        type: "Semester exams & Online portals",
        eligibility: "Graduation in any stream",
        careerSupport: false,
        syllabus: ["Sales Strategy", "Brand Promotion", "Advertising and PR", "Direct Marketing Models"],
        imageColor: "linear-gradient(135deg, #0e1e38, #457b9d)"
    },

    // --- SCDOE (Online) ---
    {
        id: "scdoe-pgdba",
        title: "Post Graduate Diploma in Business Administration (PGDBA)",
        university: "SCDOE (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 70000,
        rating: 4.4,
        reviewsCount: 3500,
        type: "Virtual classrooms & Study Kit",
        eligibility: "Bachelor's degree in any discipline",
        careerSupport: false,
        syllabus: ["Business communication", "Marketing management", "Finance structures", "Managerial Economics"],
        imageColor: "linear-gradient(135deg, #003366, #0066cc)"
    },

    // --- Sharda (Online) ---
    {
        id: "sharda-bca",
        title: "Online BCA (Mobile App Development)",
        university: "Sharda (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 125000,
        rating: 4.4,
        reviewsCount: 450,
        type: "Online lectures + Sandbox lab environments",
        eligibility: "12th Standard Passed",
        careerSupport: true,
        syllabus: ["iOS App Development", "Android SDK Integration", "User Interface Engineering", "Cloud API Hooks"],
        imageColor: "linear-gradient(135deg, #1b5e20, #388e3c)"
    },
    {
        id: "sharda-mba",
        title: "Online MBA (Global Marketing Focus)",
        university: "Sharda (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 200000,
        rating: 4.5,
        reviewsCount: 520,
        type: "Interactive weekend programs",
        eligibility: "Bachelor's degree with minimum 50% marks",
        careerSupport: true,
        syllabus: ["International Trade Rules", "Cross-cultural Marketing", "Global Finance Analytics", "Corporate Negotiations"],
        imageColor: "linear-gradient(135deg, #1b5e20, #66bb6a)"
    },

    // --- SMU (Online) ---
    {
        id: "smu-bca",
        title: "Online BCA (Software Engineering Track)",
        university: "SMU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 120000,
        rating: 4.5,
        reviewsCount: 840,
        type: "Online learning portals with LMS",
        eligibility: "10+2 with basic math knowledge",
        careerSupport: true,
        syllabus: ["System Programming", "C++ Concepts", "Web application development", "Software Testing Basics"],
        imageColor: "linear-gradient(135deg, #bf360c, #e64a19)"
    },
    {
        id: "smu-mba",
        title: "Online MBA (General Administration Options)",
        university: "SMU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 175000,
        rating: 4.6,
        reviewsCount: 1100,
        type: "Recorded & live combination schedules",
        eligibility: "Bachelor's degree from recognized university",
        careerSupport: true,
        syllabus: ["Strategic Management", "Organizational development", "Human Resource Systems", "Finance Policies"],
        imageColor: "linear-gradient(135deg, #bf360c, #ff7043)"
    },

    // --- SRM (Online) ---
    {
        id: "srm-bca",
        title: "Online BCA (Database Systems)",
        university: "SRM (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 140000,
        rating: 4.5,
        reviewsCount: 920,
        type: "Weekend Live Classes",
        eligibility: "12th Standard Passed (any stream)",
        careerSupport: true,
        syllabus: ["SQL Server Administration", "Oracle SQL Developer", "NoSQL Foundations", "Database Clustering"],
        imageColor: "linear-gradient(135deg, #0d3b66, #f4d35e)"
    },
    {
        id: "srm-mca",
        title: "Online MCA in Data Analytics",
        university: "SRM (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 190000,
        rating: 4.7,
        reviewsCount: 1400,
        type: "Live Interactive webinars & hands-on code sessions",
        eligibility: "BCA/B.Sc. in CS or Mathematics in 12th",
        careerSupport: true,
        syllabus: ["Statistics for Analytics", "Tableau Data Visualization", "R and Python Frameworks", "Hadoop & Spark Analytics"],
        imageColor: "linear-gradient(135deg, #0d3b66, #f95738)"
    },

    // --- UPES (Online) ---
    {
        id: "upes-bba",
        title: "Online BBA in Aviation Management",
        university: "UPES (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 160000,
        rating: 4.6,
        reviewsCount: 540,
        type: "Self-Paced with Live Expert Interventions",
        eligibility: "12th Standard Passed (min 50%)",
        careerSupport: true,
        syllabus: ["Aviation Operations", "Airport Planning & Design", "Passenger Services", "Logistics Strategy"],
        imageColor: "linear-gradient(135deg, #002244, #1f4e79)"
    },
    {
        id: "upes-mba",
        title: "Online MBA (Oil & Gas Management)",
        university: "UPES (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 290000,
        rating: 4.8,
        reviewsCount: 1100,
        type: "Weekly Webinars + Industry Case Studies",
        eligibility: "Graduate degree with min 50% aggregate",
        careerSupport: true,
        syllabus: ["Petroleum Regulation", "Energy Markets Macroeconomics", "Safety & Operations Management", "Renewable Resource Strategy"],
        imageColor: "linear-gradient(135deg, #002244, #0077b6)"
    },

    // --- UU (Online) ---
    {
        id: "uu-bca",
        title: "Online BCA (Systems Design & Analysis)",
        university: "UU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 100000,
        rating: 4.3,
        reviewsCount: 220,
        type: "Standard online syllabus & exams",
        eligibility: "10+2 equivalent with basic math stream",
        careerSupport: true,
        syllabus: ["Algorithm Design", "Information System Modelling", "Software Development Cycle", "Intro to Databases"],
        imageColor: "linear-gradient(135deg, #370617, #6a040f)"
    },
    {
        id: "uu-mca",
        title: "Online MCA (Advanced Application Development)",
        university: "UU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 145000,
        rating: 4.5,
        reviewsCount: 390,
        type: "Recorded & interactive web panels",
        eligibility: "BCA / Bachelor's in CS / IT",
        careerSupport: true,
        syllabus: ["Advanced Java Coding", "Cloud Infrastructure Dev", "Cyber Threat Landscapes", "Dynamic Programming Projects"],
        imageColor: "linear-gradient(135deg, #370617, #d00000)"
    },

    // --- VGU (Online) ---
    {
        id: "vgu-bca",
        title: "Online BCA (Data Science Focus)",
        university: "VGU (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 115000,
        rating: 4.4,
        reviewsCount: 310,
        type: "Online assignments and LMS classes",
        eligibility: "12th Standard in any stream",
        careerSupport: true,
        syllabus: ["Data Mining", "Foundations of AI", "Python Scripting", "Database Query Languages"],
        imageColor: "linear-gradient(135deg, #03071e, #370617)"
    },
    {
        id: "vgu-mba",
        title: "Online MBA (Agri-Business Management)",
        university: "VGU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 160000,
        rating: 4.5,
        reviewsCount: 420,
        type: "Live seminars & project implementations",
        eligibility: "Bachelor's degree in any discipline",
        careerSupport: true,
        syllabus: ["Agri-Products Economics", "Cold Chain Logistics", "Agri-Supply Optimization", "Rural Marketing Strategies"],
        imageColor: "linear-gradient(135deg, #03071e, #f72585)"
    },

    // --- VIT (Online) ---
    {
        id: "vit-mba",
        title: "Online MBA (Core Management Focus)",
        university: "VIT (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 250000,
        rating: 4.7,
        reviewsCount: 1550,
        type: "Recorded Videos + Weekly Q&A Panels",
        eligibility: "Bachelor's degree with min 50% marks",
        careerSupport: true,
        syllabus: ["Marketing Administration", "HR Strategy Development", "Financial Accounting & Modeling", "Operations Research Models"],
        imageColor: "linear-gradient(135deg, #2b1100, #5c2c16)"
    },
    {
        id: "vit-mca",
        title: "Online MCA in Software Engineering",
        university: "VIT (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 210000,
        rating: 4.8,
        reviewsCount: 2010,
        type: "Direct VIT Learning Portal Interaction",
        eligibility: "Bachelor's degree with Mathematics stream",
        careerSupport: true,
        syllabus: ["Full Stack Engineering", "DevOps & Cloud Orchestration", "Mobile Application Architecture", "Project Quality Metrics"],
        imageColor: "linear-gradient(135deg, #2b1100, #8d4f2a)"
    },

    // --- VU (Online) ---
    {
        id: "vu-mca",
        title: "Online MCA (Advanced Application Development)",
        university: "VU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 150000,
        rating: 4.4,
        reviewsCount: 410,
        type: "Recorded & interactive web panels",
        eligibility: "BCA / Bachelor's in CS / IT",
        careerSupport: true,
        syllabus: ["Enterprise Java Coding", "Cloud Infrastructure Development", "Cyber Security", "Web Frameworks"],
        imageColor: "linear-gradient(135deg, #10002b, #3c096c)"
    },
    {
        id: "vu-mba",
        title: "Online MBA (Finance / Marketing Dynamics)",
        university: "VU (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 190000,
        rating: 4.6,
        reviewsCount: 520,
        type: "LMS interactive classes",
        eligibility: "Graduation degree with min 50% aggregate",
        careerSupport: true,
        syllabus: ["Risk Management", "Product Strategy Development", "Consumer Psychology", "Portfolio Analytics"],
        imageColor: "linear-gradient(135deg, #10002b, #7b2cbf)"
    },

    // --- JIIT (Online) ---
    {
        id: "jiit-mtech",
        title: "Online M.Tech in Computer Science & Engineering",
        university: "JIIT (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Computer Science",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 210000,
        rating: 4.7,
        reviewsCount: 380,
        type: "Online lectures + Lab assignments on virtual environments",
        eligibility: "B.Tech/BE in CS/IT or MCA/M.Sc. in CS",
        careerSupport: true,
        syllabus: ["Advanced Algorithmic Design", "Cryptography & Secure Systems", "Distributed Cloud Architecture", "Deep Learning Models"],
        imageColor: "linear-gradient(135deg, #03071e, #1a0f30)"
    },

    // --- Birchwood (Executive) ---
    {
        id: "birchwood-mba",
        title: "Global Executive MBA",
        university: "Birchwood (Executive)",
        mode: "Executive",
        level: "PG",
        category: "Management",
        duration: "1 Year",
        durationWeeks: 52,
        cost: 450000,
        rating: 4.6,
        reviewsCount: 310,
        type: "Live weekend interactive cohorts",
        eligibility: "Bachelor's degree with min 2 years of work experience",
        careerSupport: true,
        syllabus: ["Global Leadership Models", "Macroeconomics and Corporate Strategy", "Venture Investments", "Innovation Management"],
        imageColor: "linear-gradient(135deg, #143601, #244f0b)"
    },

    // --- EIMT (Executive) ---
    {
        id: "eimt-ds",
        title: "Executive Certificate in Data Science",
        university: "EIMT (Executive)",
        mode: "Executive",
        level: "PG",
        category: "Data Science",
        duration: "9 Months",
        durationWeeks: 36,
        cost: 380000,
        rating: 4.8,
        reviewsCount: 220,
        type: "Live interactive international cohort lectures",
        eligibility: "Bachelor's degree in quantitative field or IT background",
        careerSupport: true,
        syllabus: ["Python Programming for Analysis", "Deep Neural Networks", "Natural Language Processing", "Cloud MLOps Pipeline"],
        imageColor: "linear-gradient(135deg, #0b1f3b, #1d3557)"
    },

    // --- UpGrad (Executive) ---
    {
        id: "upgrad-mba",
        title: "Executive MBA in Global Business",
        university: "UpGrad (Executive)",
        mode: "Executive",
        level: "PG",
        category: "Management",
        duration: "18 Months",
        durationWeeks: 72,
        cost: 320000,
        rating: 4.8,
        reviewsCount: 2450,
        type: "Cohort-based Online Classes + Campus visits",
        eligibility: "Graduation with minimum 3 years of work experience",
        careerSupport: true,
        syllabus: ["Global Trade Macroeconomics", "Mergers and Acquisitions", "Corporate Restructuring", "Executive Communication Strategy"],
        imageColor: "linear-gradient(135deg, #1c1c1c, #3d0c02)"
    },

    // --- FCU (Executive) ---
    {
        id: "fcu-mba",
        title: "Executive MBA (Strategic Management)",
        university: "FCU (Executive)",
        mode: "Executive",
        level: "PG",
        category: "Management",
        duration: "1 Year",
        durationWeeks: 52,
        cost: 290000,
        rating: 4.5,
        reviewsCount: 190,
        type: "Self-paced modules + Live masterclasses",
        eligibility: "Bachelor's degree with min 2 years of work experience",
        careerSupport: true,
        syllabus: ["Competitive Strategy", "Corporate Governance Rules", "Leadership Development", "Digital Transformation Management"],
        imageColor: "linear-gradient(135deg, #2b2d42, #1b263b)"
    },

    // --- BOSSE (Regular) ---
    {
        id: "bosse-12",
        title: "Secondary Education Certification (Grade 12 Equivalent)",
        university: "BOSSE (Regular)",
        mode: "Distance",
        level: "UG",
        category: "Arts / Humanities",
        duration: "1 Year",
        durationWeeks: 52,
        cost: 25000,
        rating: 4.1,
        reviewsCount: 1400,
        type: "Regular schooling classes / Board Examinations",
        eligibility: "Class 10th Passed",
        careerSupport: false,
        syllabus: ["English Language", "General Science Foundations", "Social Studies Studies", "Mathematics Fundamentals"],
        imageColor: "linear-gradient(135deg, #22577a, #38a3a5)"
    },

    // --- MUFTEL (F-Tel) ---
    {
        id: "muftel-telecom",
        title: "PG Program in Telecom Management",
        university: "MUFTEL (F-Tel)",
        mode: "Distance",
        level: "PG",
        category: "Management",
        duration: "1 Year",
        durationWeeks: 52,
        cost: 110000,
        rating: 4.4,
        reviewsCount: 180,
        type: "Recorded & live technical classes",
        eligibility: "BE/B.Tech or B.Sc. in Electronics / IT / Telecom",
        careerSupport: true,
        syllabus: ["Wireless Network Technologies", "Telecom Economics & Operations", "Regulatory Policies", "IoT & Future Networks"],
        imageColor: "linear-gradient(135deg, #023e8a, #0077b6)"
    },

    // --- MUODL (Distance) ---
    {
        id: "muodl-bcom",
        title: "Distance B.Com (Business Commerce)",
        university: "MUODL (Distance)",
        mode: "Distance",
        level: "UG",
        category: "Commerce",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 85000,
        rating: 4.3,
        reviewsCount: 950,
        type: "Study Material (SLM) + Periodic Mentoring",
        eligibility: "12th Standard Passed (any stream)",
        careerSupport: false,
        syllabus: ["Financial Accounting Basics", "Corporate Regulations", "Income Tax Rules", "Auditing Guidelines"],
        imageColor: "linear-gradient(135deg, #42033d, #7c1158)"
    },
    {
        id: "muodl-bba",
        title: "Distance BBA (General Business Management)",
        university: "MUODL (Distance)",
        mode: "Distance",
        level: "UG",
        category: "Management",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 95000,
        rating: 4.4,
        reviewsCount: 1120,
        type: "Correspondence study materials + assessments",
        eligibility: "Class 12th completion (any stream)",
        careerSupport: false,
        syllabus: ["Business communication", "Marketing management", "Basic Business Law", "Economics foundations"],
        imageColor: "linear-gradient(135deg, #42033d, #aa167d)"
    },

    // --- MUOL (Online) ---
    {
        id: "muol-bca",
        title: "Online BCA (General Computing)",
        university: "MUOL (Online)",
        mode: "OL/ODL",
        level: "UG",
        category: "Computer Science",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 125000,
        rating: 4.5,
        reviewsCount: 780,
        type: "100% Online study modules",
        eligibility: "Class 12th passed (any stream)",
        syllabus: ["Core Programming Concepts", "Databases", "Networking", "Software Engineering"],
        imageColor: "linear-gradient(135deg, #1b263b, #000814)",
        careerSupport: true
    },
    {
        id: "muol-mba",
        title: "Online MBA (Corporate Management)",
        university: "MUOL (Online)",
        mode: "OL/ODL",
        level: "PG",
        category: "Management",
        duration: "2 Years",
        durationWeeks: 104,
        cost: 220000,
        rating: 4.7,
        reviewsCount: 1240,
        type: "Live webinars + Group tasks",
        eligibility: "Bachelor's degree with 50% aggregate",
        careerSupport: true,
        syllabus: ["Strategic Decision Models", "Consumer Behaviors", "Macroeconomics", "Organizational Leadership"],
        imageColor: "linear-gradient(135deg, #1b263b, #003566)"
    },

    // --- SVSU (Distance) ---
    {
        id: "svsu-ba",
        title: "Distance Bachelor of Arts (BA Core Studies)",
        university: "SVSU (Distance)",
        mode: "Distance",
        level: "UG",
        category: "Arts / Humanities",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 60000,
        rating: 4.2,
        reviewsCount: 1400,
        type: "SLM Study Material Books + Annual Examinations",
        eligibility: "12th Standard Passed (any stream)",
        careerSupport: false,
        syllabus: ["History of Modern India", "Political Systems Principles", "English Language Studies", "Sociology Foundations"],
        imageColor: "linear-gradient(135deg, #1b0000, #3e2723)"
    },
    {
        id: "svsu-bcom",
        title: "Distance Bachelor of Commerce (B.Com General)",
        university: "SVSU (Distance)",
        mode: "Distance",
        level: "UG",
        category: "Commerce",
        duration: "3 Years",
        durationWeeks: 156,
        cost: 65000,
        rating: 4.3,
        reviewsCount: 890,
        type: "Correspondence study books + Annual exam centers",
        eligibility: "12th Standard passed (any stream)",
        careerSupport: false,
        syllabus: ["Accounting principles", "Business law and codes", "Macroeconomics", "Auditing Basics"],
        imageColor: "linear-gradient(135deg, #1b0000, #5c2c16)"
    }
];
